language: php
php:
  - '7.0'
install : composer install
script:
  - mkdir -p build/logs
  - vendor/bin/phpspec run
  - vendor/bin/php-coveralls -x build/logs/clover.xml 
after_success:
  - travis_retry vendor/bin/php-coveralls -v
  